export default {
	darkMode: ['class'],
	content: ['./app/**/*.{js,ts,jsx,tsx,mdx}'],
	theme: {
		extend: {
			colors: {
				'ctp-mocha-rosewater': 'var(--color-ctp-mocha-rosewater)',
				'ctp-mocha-flamingo': 'var(--color-ctp-mocha-flamingo)',
				'ctp-mocha-pink': 'var(--color-ctp-mocha-pink)',
				'ctp-mocha-mauve': 'var(--color-ctp-mocha-mauve)',
				'ctp-mocha-red': 'var(--color-ctp-mocha-red)',
				'ctp-mocha-maroon': 'var(--color-ctp-mocha-maroon)',
				'ctp-mocha-peach': 'var(--color-ctp-mocha-peach)',
				'ctp-mocha-yellow': 'var(--color-ctp-mocha-yellow)',
				'ctp-mocha-green': 'var(--color-ctp-mocha-green)',
				'ctp-mocha-teal': 'var(--color-ctp-mocha-teal)',
				'ctp-mocha-sky': 'var(--color-ctp-mocha-sky)',
				'ctp-mocha-sapphire': 'var(--color-ctp-mocha-sapphire)',
				'ctp-mocha-blue': 'var(--color-ctp-mocha-blue)',
				'ctp-mocha-lavender': 'var(--color-ctp-mocha-lavender)',
				'ctp-mocha-text': 'var(--color-ctp-mocha-text)',
				'ctp-mocha-subtext1': 'var(--color-ctp-mocha-subtext1)',
				'ctp-mocha-subtext0': 'var(--color-ctp-mocha-subtext0)',
				'ctp-mocha-overlay2': 'var(--color-ctp-mocha-overlay2)',
				'ctp-mocha-overlay1': 'var(--color-ctp-mocha-overlay1)',
				'ctp-mocha-overlay0': 'var(--color-ctp-mocha-overlay0)',
				'ctp-mocha-surface2': 'var(--color-ctp-mocha-surface2)',
				'ctp-mocha-surface1': 'var(--color-ctp-mocha-surface1)',
				'ctp-mocha-surface0': 'var(--color-ctp-mocha-surface0)',
				'ctp-mocha-base': 'var(--color-ctp-mocha-base)',
				'ctp-mocha-mantle': 'var(--color-ctp-mocha-mantle)',
				'ctp-mocha-crust': 'var(--color-ctp-mocha-crust)',

				// Latte palette (para o modo claro)
				'ctp-latte-rosewater': 'var(--color-ctp-latte-rosewater)',
				'ctp-latte-flamingo': 'var(--color-ctp-latte-flamingo)',
				'ctp-latte-pink': 'var(--color-ctp-latte-pink)',
				'ctp-latte-mauve': 'var(--color-ctp-latte-mauve)',
				'ctp-latte-red': 'var(--color-ctp-latte-red)',
				'ctp-latte-maroon': 'var(--color-ctp-latte-maroon)',
				'ctp-latte-peach': 'var(--color-ctp-latte-peach)',
				'ctp-latte-yellow': 'var(--color-ctp-latte-yellow)',
				'ctp-latte-green': 'var(--color-ctp-latte-green)',
				'ctp-latte-teal': 'var(--color-ctp-latte-teal)',
				'ctp-latte-sky': 'var(--color-ctp-latte-sky)',
				'ctp-latte-sapphire': 'var(--color-ctp-latte-sapphire)',
				'ctp-latte-blue': 'var(--color-ctp-latte-blue)',
				'ctp-latte-lavender': 'var(--color-ctp-latte-lavender)',
				'ctp-latte-text': 'var(--color-ctp-latte-text)',
				'ctp-latte-subtext1': 'var(--color-ctp-latte-subtext1)',
				'ctp-latte-subtext0': 'var(--color-ctp-latte-subtext0)',
				'ctp-latte-overlay2': 'var(--color-ctp-latte-overlay2)',
				'ctp-latte-overlay1': 'var(--color-ctp-latte-overlay1)',
				'ctp-latte-overlay0': 'var(--color-ctp-latte-overlay0)',
				'ctp-latte-surface2': 'var(--color-ctp-latte-surface2)',
				'ctp-latte-surface1': 'var(--color-ctp-latte-surface1)',
				'ctp-latte-surface0': 'var(--color-ctp-latte-surface0)',
				'ctp-latte-base': 'var(--color-ctp-latte-base)',
				'ctp-latte-mantle': 'var(--color-ctp-latte-mantle)',
				'ctp-latte-crust': 'var(--color-ctp-latte-crust)',
			},
		},
	},
	plugins: [],
}
